# Generated by Django 5.2.4 on 2025-07-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="vote",
            field=models.CharField(
                choices=[("W", "Wrong"), ("A", "Abstained"), ("R", "Right")],
                default="A",
                max_length=1,
            ),
        ),
    ]
