# Generated by Django 5.2.4 on 2025-07-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="theme",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
