# Generated by Django 5.2.4 on 2025-07-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_event_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="theme",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
