# Generated by Django 5.2.4 on 2025-07-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_vote_vote"),
    ]

    operations = [
        migrations.CreateModel(
            name="Glossary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("acronym", models.CharField(max_length=20, unique=True)),
                ("definition", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="vote",
            name="vote",
            field=models.CharField(
                choices=[("R", "Right"), ("W", "Wrong"), ("A", "Abstained")],
                default="A",
                max_length=1,
            ),
        ),
    ]
