# Generated by Django 5.2.4 on 2025-07-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_glossary_alter_vote_vote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="vote",
            field=models.CharField(
                choices=[("A", "Abstained"), ("R", "Right"), ("W", "Wrong")],
                default="A",
                max_length=1,
            ),
        ),
    ]
