# Generated by Django 5.2.4 on 2025-07-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_vote_vote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="vote",
            field=models.CharField(
                choices=[("R", "Right"), ("W", "Wrong"), ("A", "Abstained")],
                default="A",
                max_length=1,
            ),
        ),
    ]
