# Generated by Django 5.2.4 on 2025-07-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_table_alter_team_team_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
