# Generated by Django 5.2.4 on 2025-07-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_table_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Optional name for the table",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
    ]
