# Generated by Django 5.2.4 on 2025-07-22 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_vote_vote"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="glossary",
            options={
                "verbose_name": "Glossary Entry",
                "verbose_name_plural": "Glossary Entries",
            },
        ),
    ]
