# Generated by Django 5.2.4 on 2025-07-20 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_table_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="quizmaster_table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.table",
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
