# Generated by Django 5.2.4 on 2025-07-24 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_glossary_options"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="memberattendance",
            name="unique_member_event",
        ),
        migrations.RemoveConstraint(
            model_name="teameventparticipation",
            name="unique_team_event",
        ),
        migrations.AlterField(
            model_name="event",
            name="quizmaster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events_as_quizmaster",
                to="api.quizmaster",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="quizmaster_table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events_as_quizmaster_table",
                to="api.table",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events_with_theme",
                to="api.theme",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="teameventparticipation",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams_participating",
                to="api.event",
            ),
        ),
        migrations.AlterField(
            model_name="teameventparticipation",
            name="table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_participations_at_table",
                to="api.table",
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes_in_event",
                to="api.event",
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes_in_round",
                to="api.round",
            ),
        ),
        migrations.AddConstraint(
            model_name="member",
            constraint=models.UniqueConstraint(
                fields=("name", "team"), name="unique_team_member"
            ),
        ),
        migrations.AddConstraint(
            model_name="memberattendance",
            constraint=models.UniqueConstraint(
                fields=("member", "event"), name="unique_member_event_attendance"
            ),
        ),
        migrations.AddConstraint(
            model_name="teameventparticipation",
            constraint=models.UniqueConstraint(
                fields=("team", "event"), name="unique_team_event_participation"
            ),
        ),
    ]
