# Generated by Django 5.2.4 on 2025-07-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_event_quizmaster_table_alter_table_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teameventparticipation",
            name="score",
            field=models.PositiveIntegerField(),
        ),
    ]
