# Generated by Django 5.2.4 on 2025-07-21 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_teameventparticipation_score"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="memberattendance",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="teameventparticipation",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="teameventparticipation",
            name="table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_event_participations",
                to="api.table",
            ),
        ),
        migrations.AddConstraint(
            model_name="memberattendance",
            constraint=models.UniqueConstraint(
                fields=("member", "event"), name="unique_member_event"
            ),
        ),
        migrations.AddConstraint(
            model_name="teameventparticipation",
            constraint=models.UniqueConstraint(
                fields=("team", "event"), name="unique_team_event"
            ),
        ),
    ]
