# Generated by Django 5.2.4 on 2025-07-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_memberattendance_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teameventparticipation",
            name="score",
            field=models.IntegerField(),
        ),
    ]
