# Generated by Django 5.2.4 on 2025-07-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_teameventparticipation_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="team_id",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                fields=("date", "quizmaster"), name="unique_event"
            ),
        ),
    ]
