# Generated by Django 5.2.4 on 2025-07-22 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_event_date_alter_team_team_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="event",
            name="quizmaster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="api.quizmaster",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="quizmaster_table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="api.table",
            ),
        ),
        migrations.AlterField(
            model_name="memberattendance",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_attendances",
                to="api.event",
            ),
        ),
        migrations.AlterField(
            model_name="memberattendance",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_attendances",
                to="api.member",
            ),
        ),
        migrations.AlterField(
            model_name="teameventparticipation",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_participations",
                to="api.event",
            ),
        ),
        migrations.AlterField(
            model_name="teameventparticipation",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_participations",
                to="api.team",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="api.theme",
            ),
        ),
    ]
